package:
  name: sciencetools-scons
  version: "0test"

source:
  git_url: https://github.com/fermi-lat/ScienceTools.git

build:
  number: 1

requirements:
  build:
    - scons 2.*
    - fermi-repoman
    - ape
    - f2c
    - root5
    - python
    - astropy
    - cppunit
    - clhep
    - distribute
    - fftw
    - gsl
    - matplotlib
    - numpy
    - pmw
    - scipy
    - swig
    - xerces-c
    - healpix_cxx
    - wcslib

  run:
    - ape
    - root5
    - f2c
    - minuit2
    - python
    - astropy
    - cppunit
    - clhep
    - distribute
    - fftw
    - gsl
    - matplotlib
    - numpy
    - pmw
    - scipy
    - swig
    - xerces-c
    - healpix_cxx
    - wcslib

