{% set name = "fermitools" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/fermi-lat/ScienceTools.git

build:
  number: {{ environ.get('BUILD_NUMBER', 0)}}
  skip: true  # [win]


requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    #- gcc 4.8.5 # [linux]  
    #- scons 2.*
    #- fermi-repoman
    
  host:
    #- {{ compiler('c') }}
    #- {{ compiler('cxx') }}
    #- {{ compiler('fortran') }}
    - ape
    - aplpy
    - astropy
    - blas
    - clhep
    - cppunit
    - f2c
    - fermi-repoman
    - fftw
    - git
    - gsl
    - healpix_cxx
    - matplotlib
    - numpy
    - openblas
    - pmw
    - readline
    - root5 5.34.38
    - scons
    - swig
    - wcslib
    - xerces-c

  run:
    - ape
    - aplpy
    - astropy
    - blas
    - clhep 
    - cppunit
    - f2c
    - fftw
    - fermitools-data >=0.16 # This must be updated with every model release
    - gsl
    - healpix_cxx
    - matplotlib
    - ncurses
    - numpy 
    - openblas
    - pmw
    - pyyaml
    - readline
    - root5 5.34.38
    - scipy
    - wcslib
    - xerces-c

test:
  imports:
    - UnbinnedAnalysis
    - pyLikelihood

  commands:
    # These tests inspect linkages and libraries. They are very slow, so comment them out
    # for a quicker turnaround when testing
    #- conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    #- conda inspect objects -p $PREFIX {{ name }}  # [osx]

