{% set name = "fermitools" %}
{% set version = "1.9.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/fermi-lat/ScienceTools.git

build:
  number: {{ environ.get('BUILD_NUMBER', 0)}}
  skip: true  # [win]


requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - ape >=3
    - aplpy
    - astropy
    - blas
    - clhep
    - cppunit
    - f2c 0.0.2
    - fermi-repoman
    - fftw
    - git
    - gsl
    - healpix_cxx
    - matplotlib
    - numpy >=1.17
    - openblas
    - pmw
    - python 3.7.*
    - readline
    - root >=6.0
    - scons 3.0.3
    - swig
    - wcslib 5.*
    - xerces-c
    - zstd 1.3.7

  run:
    - ape >=3
    - aplpy
    - astropy
    - blas
    - clhep 
    - cppunit
    - f2c 0.0.2
    - fftw
    - fermitools-data >=0.16 # This must be updated with every model release
    - gsl
    - healpix_cxx
    - matplotlib
    - ncurses
    - numpy  >=1.17
    - openblas
    - pmw
    - python 3.7.*
    - pyyaml
    - readline
    - root >=6.0
    - scipy
    - wcslib 5.*
    - xerces-c
    - zstd 1.3.7

test:
  imports:
    - UnbinnedAnalysis
    - pyLikelihood

  commands:
    # These tests inspect linkages and libraries. They are very slow, so comment them out
    # for a quicker turnaround when testing
    #- conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    #- conda inspect objects -p $PREFIX {{ name }}  # [osx]

