{% set name = "fermitools" %}
{% set version = "0.0.1b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/fermi-lat/ScienceTools.git

build:
  number: 0
  skip: true  # [win]
  skip: true  # [py3k]

requirements:
  build:
    - ape
    - aplpy
    - astropy
    - blas
    - clhep
    - cppunit
    - f2c
    - fermi-repoman
    - fftw
    - git
    - gsl
    - healpix_cxx
    - matplotlib
    - numpy 1.11.*
    - openblas 0.2.19|0.2.19.*
    - pmw
    - python
    - readline 6.2
    - root5
    - scons 2.*
    - swig
    - toolchain
    - wcslib
    - xerces-c

  run:
    - ape
    - aplpy
    - astropy
    - blas
    - clhep
    - cppunit
    - f2c
    - fftw
    - gsl
    - healpix_cxx
    - matplotlib
    - numpy >=1.11
    - openblas 0.2.19|0.2.19.*
    - pmw
    - python
    - readline 6.2
    - root5
    - scipy
    - wcslib
    - xerces-c

test:
  commands:
    # These tests inspect linkages and libraries. They are very slow, so comment them out
    # for a quicker turnaround when testing
    #- conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    #- conda inspect objects -p $PREFIX {{ name }}  # [osx]
