{% set name = "fermitools" %}
{% set version = "1.2.23" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/fermi-lat/ScienceTools.git

build:
  number: {{ environ.get('BUILD_NUMBER', 0)}}
  skip: true  # [win]
  skip: true  # [py3k]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    #- {{ compiler('fortran') }}
    #- gcc 4.8.5 # [linux]  
    - scons 3.0.3
    - fermi-repoman
    - root
    
  host:
    #- {{ compiler('c') }}
    #- {{ compiler('cxx') }}
    #- {{ compiler('fortran') }}
    - ape >=3.0
    - aplpy
    - astropy
    - blas 
    - clhep
    - cppunit
    - f2c 0.0.2
    - fermi-repoman
    - fftw 
    - git
    - gsl
    - healpix_cxx
    - matplotlib
    - numpy >= 1.11
    - openblas 
    - pmw 
    - python 
    - readline 
    - root
    - scons 3.0.3
    - swig 
    - wcslib 5.18
    - xerces-c

  run:
    - ape >=3.0
    - aplpy
    - astropy
    - blas 
    - clhep 
    - cppunit 
    - f2c >=0.0.3
    - fftw 
    - fermitools-data
    - gsl 
    - healpix_cxx 
    - matplotlib
    - ncurses 
    - numpy  >= 1.11
    - openblas 
    - pmw 
    - python 7
    - pyyaml
    - readline 
    - root
    - scipy
    - wcslib 
    - xerces-c 

test:
  imports:
    - UnbinnedAnalysis
    - pyLikelihood

  commands:
    # These tests inspect linkages and libraries. They are very slow, so comment them out
    # for a quicker turnaround when testing
    #- conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    #- conda inspect objects -p $PREFIX {{ name }}  # [osx]

