{% set name = "fermitools" %}
{% set version = "0.0.1b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/fermi-lat/ScienceTools.git

build:
  number: 0
  skip: true  # [win]
  skip: true  # [py3k]

requirements:
  build:
    - matplotlib
    - root5 
    - readline 6.2
    - toolchain
    - scons 2.*
    - git
    - fermi-repoman
    - ape
    - f2c
    - python
    - astropy
    - cppunit
    - clhep
    - fftw
    - gsl
    - pmw
    - swig
    - xerces-c 
    - healpix_cxx
    - wcslib
    - blas
    - openblas 0.2.19|0.2.19.*

  run:
    - numpy >=1.11
    - ape
    - root5
    - f2c
    - python
    - astropy
    - cppunit
    - clhep
    - fftw
    - gsl
    - matplotlib
    - numpy
    - pmw
    - scipy
    - swig
    - xerces-c
    - healpix_cxx
    - wcslib
    - openblas 0.2.19|0.2.19.*
    - readline 6.2

test:
  commands:
    - conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    - conda inspect objects -p $PREFIX {{ name }}  # [osx]
