{% set name = "fermitools" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/fermi-lat/ScienceTools.git

build:
  number: {{ environ.get('BUILD_NUMBER', 0)}}
  skip: true  # [win]
  skip: true  # [py3k]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    
  host:
    - ape 2.9
    - aplpy
    - astropy
    - blas 1.1
    - clhep 2.4.1.0
    - cppunit 1.14.0
    - f2c 0.0.1
    - fermi-repoman
    - fftw 3.3.8
    - git
    - gsl 2.2
    - healpix_cxx 3.31
    - matplotlib >=2.2
    - numpy 1.16.0
    - openblas 0.3.2
    - pmw 2.0.1
    - python 2.7
    - readline 
    - root5 5.34.38
    - scons 2.*
    - swig 3.0.12
    - wcslib 5.18
    - xerces-c 3.2.0

  run:
    - ape 2.9
    - aplpy
    - astropy
    - blas 1.1
    - clhep 2.4.1.0
    - cppunit 1.14.0
    - f2c 0.0.1
    - fftw 3.3.8
    - fermitools-data >=0.11 # This must be updated with every model release
    - gsl 2.2
    - healpix_cxx 3.31
    - matplotlib >=2.2
    - ncurses <6.0
    - numpy 1.16.0
    - openblas 0.3.2
    - pmw 2.0.1
    - python 2.7
    - pyyaml
    - readline 
    - root5 5.34.38
    - scipy 1.2.0
    - wcslib 5.18
    - xerces-c 3.2.0

test:
  imports:
    - UnbinnedAnalysis
    - pyLikelihood

  commands:
    # These tests inspect linkages and libraries. They are very slow, so comment them out
    # for a quicker turnaround when testing
    #- conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    #- conda inspect objects -p $PREFIX {{ name }}  # [osx]

